title: Pybricks Competition Tutorial
description: >-
  Pybricks Competition Tutorial - using Pybricks framework in FIRST LEGO League and World Robot Olympiad competitions.
keywords: FLL, WRO, Pybricks, LEGO
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  afarago
repository: afarago/pybricks-competition-tutorial.attilafarago.hu
# https://just-the-docs.com/docs/configuration/#footer-content

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme

favicon_ico: "/assets/favicon.ico"
# logo: "/assets/icon_320x320.png"

search_enabled: true
nav_enabled: true
heading_anchors: true

# Footer "Edit this page on GitHub" link text
gh_edit_link: false # show or hide edit this page link

# Footer content
# appears at the bottom of every page's main content
# Note: The footer_content option is deprecated and will be removed in a future major release. Please use `_includes/footer_custom.html` for more robust markup / liquid-based content.
footer_content: "Copyright &copy; 2024 Attila Farago."

callouts:
  warning:
    title: WARNING
    color: red
  highlight:
    color: yellow
  task:
    title: EXERCISE
    color: yellow
  task_solution:
    title: MY SOLUTION
    color: greenyellow

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true
aux_links:
  "<i alt='homepage'  class='fa-xl fa-solid fa-user'></i>":
    - "https://attilafarago.hu"
  "<i alt='pybricks'  class='fa-xl fa-solid fa-robot'></i>":
    - "https://pybricks.com"

exclude:
  - Gemfile
  - Gemfile.lock
  - "*README*"


# Reference:
# https://just-the-docs.com/